# Default configuration for Security MCP Server

server:
  name: "security-mcp-server"
  version: "2.0.0"
  debug: false

modules:
  # List of modules to enable (empty = all discovered modules)
  enabled: []
  
  # Module loading order
  load_order:
    - example
    - nuclei
    - shodan
    - leakcheck

security:
  # Target validation settings
  allowed_target_types:
    - url
    - ip
    - domain
  
  # Rate limiting
  rate_limits:
    requests_per_minute: 60
    max_concurrent_tools: 5
  
  # Input sanitization
  max_input_length: 1000
  
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null  # Optional log file path
